Map<String, String> arabicLanguage = {
  "HotNews": "الاخبار",
  "Categories": "فئات",
  "News": "الاخبار",
  "No Data": "لايوجد بيانات",
  "No Description": "......لا يوجد وصف",
  "Best Experience To See News Around The Word":
      "أفضل تجربة لمشاهدة الأخبار حول العالم",
  "Next": "التالي",
  "Filter": "فلترة",
  "Favorite": "المفضلة",
  "Home": "الرئيسية",
  'Help & Support': 'مساعدة & دعم',
  "Settings": "الضبط              ",
  "Remove All": "حذف الجميع",
  "Country": " اختر بلد ",
  "Sorted By": "ترتيب حسب",
  "Description": " الوصف : ",
  "No Title": "لا يوجد عنوان",
  "Content": "المحتوى :",
  "Published At": "نُشرت في:",
  "Author": "الكاتب:",
  "no author": "لا يوجد كاتب",
  "2023-07-06 15:01:27.000z": "2023-07-06 15:01:27.000z",
  "Help Support": "المساعدة و الدعم",
  "FAQ:": "التعليمات:",
  "How to use this app": "كيف استخدم هذا التطبيق",
  "You need internet to see news": "انت تحتاج للانترنت لترى الاخبار",
  "You can see all type of news from drawer then all news":
      "يمكنك رؤية جميع انواع الاخبار من الدرج ثم الاخبار",
  "You can see the type of news you want from bottom bar":
      "يمكنك رؤية نوع الأخبار التي تريدها من الشريط السفلي",
  "You can change theme or language from drawer then settings":
      "يمكنك تغيير المظهر أو اللغة من الدرج ثم الإعدادات",
  "How made this app": "كيف صنع هذا التطبيق",
  "This appa made by Hiba AL Dayoub": "هذا التطبيق من تصميم هبة الديوب",
  "Dark mode": "  الوضع المظلم",
  "Light mode": "  الوضع المضيء:",
  "Language :": "اللغة :",
  "ar": "العربية",
  "en": "الانكليزية",
  'Technology': 'التكنولوجيا',
  'Business': 'الاعمال',
  'Health': 'الصحة',
  'Science': 'العلوم',
  'Sports': 'الرياضة',
  'Italy': 'ايطاليا',
  'United Kingdom': 'المملكة المتحدة',
  'Egypt': 'مصر',
  'Canada': 'كندا',
  'Brazil': 'البرازيل',
  'Australia': 'استراليا',
  'United Arab Emirates': 'الامارات العربية المتحدة',
  'United States': 'الولايات المتحدة',
  'Russia': 'روسيا',
  'Korea': 'كوريا',
  'Newest': 'الاحدث',
  'Oldest': 'الاقدم'
};
