Map<String, String> englishLanguage = {
  "HotNews": "Hot News",
  "Categories": "Categories",
  "News": "News",
  "No Data": "No Data ",
  "No Description": "No Description ..... ..",
  "Best Experience To See News Around The Word":
      "Best Experience To See News Around The World",
  "Next": "Next",
  "Filter": "Filter",
  "Favorite": "Favorite",
  "Home": "Home",
  'Help & Support': 'Help & Support',
  "Settings": "Settings              ",
  "Remove All": "Remove All",
  "Country": "Country",
  "Sorted By": "Sorted By",
  "Description": "Description : ",
  "No Title": "No Title",
  "Content": "Content : ",
  "Published At": "Published At  : ",
  "Author": "Author : ",
  "no author": "no author",
  "2023-07-06 15:01:27.000z": "2023-07-06 15:01:27.000z",
  "Help Support": "Help Support",
  "FAQ:": "FAQ:",
  "How to use this app": "How to use this app",
  "You need internet to see news": "You need internet to see news",
  "You can see all type of news from drawer then all news":
      "You can see all type of news from drawer then all news",
  "You can see the type of news you want from bottom bar":
      "You can see the type of news you want from bottom bar",
  "You can change theme or language from drawer then settings":
      "You can change theme or language from drawer then settings",
  "How made this app": "How made this app",
  "This appa made by Hiba AL Dayoub": "This app made by Hiba AL Dayoub",
  "Dark mode": "  Dark mode",
  "Light mode": "  Light mode",
  "Language :": "Language :",
  'ar': "ar",
  'en': "en",
  'Technology': 'Technology',
  'Business': 'Business',
  'Health': 'Health',
  'Science': 'Science',
  'Sports': 'Sports',
  'Italy': 'Italy',
  'United Kingdom': 'United Kingdom',
  'Egypt': 'Egypt',
  'Canada': 'Canada',
  'Brazil': 'Brazil',
  'Australia': 'Australia',
  'United Arab Emirates': 'United Arab Emirates',
  'United States': 'United States',
  'Russia': 'Russia',
  'Korea': 'Korea',
  'Newest': 'Newest',
  'Oldest': 'Oldest'
};
